const majorToAreaMapping = {
    // STEM
    "computer science": "STEM", "cs": "STEM",
    "data science": "STEM",
    "mathematics": "STEM", "math": "STEM", "pre-mathematics": "STEM",
    "physics": "STEM",
    "chemistry": "STEM",
    "biology": "STEM", "biological sciences": "STEM", "human biology": "STEM", "integrative biology": "STEM",
    "molecular and cell biology": "STEM",
    "cell biology": "STEM",
    "molecular biology": "STEM",
    "biochemistry": "STEM",
    "neuroscience": "STEM", "cognitive science": "STEM", "cognitive studies": "STEM",
    "statistics": "STEM",
    "astrophysics": "STEM", "astronomy": "STEM",
    "environmental science": "STEM",
    "environmental science & policy": "STEM",
    "geoscience": "STEM", "geology": "STEM",
    "ecology": "STEM", "evolutionary biology": "STEM",
    "plant science": "STEM",
    "entomology": "STEM",
    "animal behavior": "STEM", "zoology": "STEM",
    "marine biology": "STEM",
    "biotechnology": "STEM",
    "information science": "STEM",
    "computer programming": "STEM",
    "cybersecurity": "STEM",
    "data analytics": "STEM", "business analytics": "STEM", // Moved business analytics here
    "robotics": "STEM",
    "meteorology": "STEM",
    "oceanography": "STEM",
    "molecular science": "STEM",
    "forestry": "STEM", "foresty": "STEM",
    "urban arboriculture": "STEM",
    "materials science": "STEM",

    // Engineering
    "engineering": "Engineering",
    "mechanical engineering": "Engineering",
    "electrical engineering": "Engineering",
    "civil engineering": "Engineering", "civil": "Engineering",
    "chemical engineering": "Engineering",
    "biomedical engineering": "Engineering", "bme": "Engineering", "biomolecular engineering": "Engineering",
    "aerospace engineering": "Engineering", "aeronautical engineering technology": "Engineering",
    "computer engineering": "Engineering",
    "industrial engineering": "Engineering",
    "software engineering": "Engineering",
    "environmental engineering": "Engineering",
    "environmental engineering and ethics": "Engineering",
    "materials engineering": "Engineering",
    "materials science & engineering": "Engineering",
    "manufacturing & design engineering": "Engineering",
    "manufacturing engineering": "Engineering", "manufacturing": "Engineering",
    "design engineering": "Engineering",

    // Business & Economics
    "business administration": "Business/Economics", "business": "Business/Economics",
    "business management": "Business/Economics", "management": "Business/Economics",
    "economics": "Business/Economics", "econ": "Business/Economics", "business economics": "Business/Economics", "financial economics": "Business/Economics", "applied economics and management": "Business/Economics",
    "economics & african american studies": "Business/Economics",
    "finance": "Business/Economics",
    "biomedical studies & finance": "Business/Economics",
    "marketing": "Business/Economics", "marketing management": "Business/Economics",
    "marketing & advertising": "Business/Economics",
    "advertising": "Business/Economics",
    "accounting": "Business/Economics",
    "international business": "Business/Economics",
    "entrepreneurship": "Business/Economics",
    "sport management": "Business/Economics",
    "information systems": "Business/Economics",
    "computer information systems": "Business/Economics",
    "actuarial science": "Business/Economics",
    "supply chain management": "Business/Economics",
    "real estate": "Business/Economics",
    "hospitality management": "Business/Economics",
    "human resources": "Business/Economics",
    "political economy": "Business/Economics",
    "philsophy & politics and economics": "Business/Economics",

    // Humanities & Social Sciences
    "english": "Humanities/Social Sciences",
    "english literature": "Humanities/Social Sciences", "literature": "Humanities/Social Sciences",
    "english language & literature": "Humanities/Social Sciences",
    "history": "Humanities/Social Sciences", "ancient history": "Humanities/Social Sciences",
    "art history": "Humanities/Social Sciences", "history of art": "Humanities/Social Sciences",
    "political science": "Humanities/Social Sciences", "polisci": "Humanities/Social Sciences", "government": "Humanities/Social Sciences", "politics": "Humanities/Social Sciences",
    "psychology": "Humanities/Social Sciences", "psych": "Humanities/Social Sciences", "applied psychology": "Humanities/Social Sciences",
    "sociology": "Humanities/Social Sciences", "society": "Humanities/Social Sciences",
    "anthropology": "Humanities/Social Sciences", "social anthropology": "Humanities/Social Sciences",
    "philosophy": "Humanities/Social Sciences", "philsophy": "Humanities/Social Sciences",
    "ethics": "Humanities/Social Sciences",
    "international relations": "Humanities/Social Sciences", "ir": "Humanities/Social Sciences", "global affairs": "Humanities/Social Sciences",
    "communications": "Humanities/Social Sciences", "communication studies": "Humanities/Social Sciences", "media studies": "Humanities/Social Sciences", "multi-cultural media": "Humanities/Social Sciences", "media arts production": "Humanities/Social Sciences",
    "linguistics": "Humanities/Social Sciences",
    "journalism": "Humanities/Social Sciences",
    "magazine, news & digital journalism": "Humanities/Social Sciences",
    "digital journalism": "Humanities/Social Sciences",
    "news": "Humanities/Social Sciences", "magazine": "Humanities/Social Sciences",
    "liberal arts": "Humanities/Social Sciences", "liberal studies": "Humanities/Social Sciences", "humanities": "Humanities/Social Sciences",
    "creative writing": "Humanities/Social Sciences",
    "public policy": "Humanities/Social Sciences", "policy studies": "Humanities/Social Sciences", "policy": "Humanities/Social Sciences",
    "environmental studies": "Humanities/Social Sciences",
    "environmental policy": "Humanities/Social Sciences",
    "africana studies": "Humanities/Social Sciences",
    "african american studies": "Humanities/Social Sciences",
    "international development": "Humanities/Social Sciences", "development": "Humanities/Social Sciences",
    "industrial and labor relations": "Humanities/Social Sciences",
    "industiral and labor relations": "Humanities/Social Sciences",
    "industrial labor relations": "Humanities/Social Sciences",
    "labor relations": "Humanities/Social Sciences",
    "archaeological studies": "Humanities/Social Sciences", "archaeology": "Humanities/Social Sciences",
    "law & society": "Humanities/Social Sciences",
    "law, history, and society": "Humanities/Social Sciences",
    "law": "Humanities/Social Sciences",
    "pre-law": "Humanities/Social Sciences",
    "criminology": "Humanities/Social Sciences",
    "criminal justice": "Humanities/Social Sciences",
    "urban studies": "Humanities/Social Sciences", "urban planning": "Humanities/Social Sciences",
    "geography": "Humanities/Social Sciences",
    "foreign languages": "Humanities/Social Sciences", "modern languages": "Humanities/Social Sciences",
    "area studies": "Humanities/Social Sciences",
    "gender studies": "Humanities/Social Sciences", "women's studies": "Humanities/Social Sciences",
    "classics": "Humanities/Social Sciences",
    "religious studies": "Humanities/Social Sciences",
    "public relations": "Humanities/Social Sciences",
    "social sciences": "Humanities/Social Sciences",
    "comparative literature": "Humanities/Social Sciences",

    // Arts & Design
    "fine arts": "Arts/Design", "art": "Arts/Design", "studio art": "Arts/Design", "visual arts": "Arts/Design", "film, photography, and visual arts": "Arts/Design",
    "graphic design": "Arts/Design", "design": "Arts/Design", "digital design": "Arts/Design", "digital design & animation": "Arts/Design",
    "music": "Arts/Design", "music performance": "Arts/Design", "music composition": "Arts/Design", "musical studies": "Arts/Design",
    "theater": "Arts/Design", "drama": "Arts/Design", "performing arts": "Arts/Design", "acting": "Arts/Design", "theatre": "Arts/Design",
    "film studies": "Arts/Design", "film": "Arts/Design", "flim": "Arts/Design",
    "cinema studies": "Arts/Design", "film production": "Arts/Design",
    "politics & flim": "Arts/Design",
    "architecture": "Arts/Design",
    "fashion design": "Arts/Design", "fashion merchandising": "Arts/Design",
    "photography": "Arts/Design",
    "animation": "Arts/Design",
    "industrial design": "Arts/Design",
    "game design": "Arts/Design",
    "game design and development": "Arts/Design",
    "collaborative arts": "Arts/Design",
    "dance": "Arts/Design",
    "interior design": "Arts/Design",
    "urban design": "Arts/Design",
    "production": "Arts/Design", "design & production": "Arts/Design",


    // Health Sciences
    "nursing": "Health Sciences",
    "pre-med": "Health Sciences", "pre-medicine": "Health Sciences", "pre-dental": "Health Sciences", "pre-health": "Health Sciences",
    "public health": "Health Sciences", "global public health": "Health Sciences", "public health science": "Health Sciences",
    "kinesiology": "Health Sciences", "exercise science": "Health Sciences",
    "pharmacy": "Health Sciences", "pre-pharmacy": "Health Sciences", "pharmacology": "Health Sciences",
    "nutrition": "Health Sciences", "food science": "Health Sciences",
    "hssp": "Health Sciences",
    "medicine, science, and the humanities": "Health Sciences",
    "medicine": "Health Sciences",
    "physical therapy": "Health Sciences",
    "occupational therapy": "Health Sciences",
    "speech pathology": "Health Sciences",
    "social work": "Health Sciences",
    "health sciences": "Health Sciences",
    "biomedical studies": "Health Sciences",

    // Education
    "education": "Education", "teaching": "Education",
    "teacher tech design": "Education",
    "secondary english education": "Education",
    "elementary education": "Education",
    "special education": "Education",

    // Undecided/Other
    "undecided major": "Undecided/Other",
    "undecided": "Undecided/Other",
    "exploratory": "Undecided/Other",
    "general studies": "Undecided/Other",
    "n/a": "Undecided/Other",
    "other": "Undecided/Other",
};
