const majorToAreaMapping = {
    // STEM
    "animal behavior": "STEM",
    "astronomy": "STEM",
    "astrophysics": "STEM",
    "biochemistry": "STEM",
    "biochemistry & molecular biology": "STEM",
    "biology": "STEM",
    "biological sciences": "STEM",
    "biotechnology": "STEM",
    "biotechnology & molecular science": "STEM",
    "cell biology": "STEM",
    "chemistry": "STEM",
    "chemistry & mathematics": "STEM",
    "cognitive science": "STEM",
    "cognitive studies": "STEM",
    "computer programming": "STEM",
    "computer science": "STEM",
    "computer science & business": "STEM",
    "cs": "STEM",
    "cybersecurity": "STEM",
    "data analytics": "STEM",
    "data science": "STEM",
    "ecology": "STEM",
    "ecology & evolutionary biology": "STEM",
    "ecology & music": "STEM",
    "entomology": "STEM",
    "environmental science": "STEM",
    "environmental science & policy": "STEM",
    "evolutionary biology": "STEM",
    "forestry": "STEM",
    "foresty": "STEM",
    "foresty & urban arboriculture": "STEM",
    "geoscience": "STEM",
    "geology": "STEM",
    "human biology": "STEM",
    "information science": "STEM",
    "integrative biology": "STEM",
    "integrative neuroscience": "STEM",
    "marine biology": "STEM",
    "materials science": "STEM",
    "mathematics": "STEM",
    "mathematics & statistics": "STEM",
    "math": "STEM",
    "meteorology": "STEM",
    "molecular and cell biology": "STEM",
    "molecular biology": "STEM",
    "molecular science": "STEM",
    "neuroscience": "STEM",
    "oceanography": "STEM",
    "physics": "STEM",
    "plant science": "STEM",
    "pre-mathematics": "STEM",
    "psychology & brain science": "STEM",
    "robotics": "STEM",
    "statistics": "STEM",
    "urban arboriculture": "STEM",
    "zoology": "STEM",

    // Engineering
    "aerospace engineering": "Engineering",
    "aeronautical engineering technology": "Engineering",
    "biomedical engineering": "Engineering",
    "bme": "Engineering",
    "biomolecular engineering": "Engineering",
    "chemical engineering": "Engineering",
    "civil": "Engineering",
    "civil engineering": "Engineering",
    "civil & environmental engineering": "Engineering",
    "computer engineering": "Engineering",
    "design engineering": "Engineering",
    "electrical engineering": "Engineering",
    "engineering": "Engineering",
    "environmental engineering": "Engineering",
    "environmental engineering and ethics": "Engineering",
    "industrial engineering": "Engineering",
    "manufacturing": "Engineering",
    "manufacturing & design engineering": "Engineering",
    "manufacturing engineering": "Engineering",
    "materials engineering": "Engineering",
    "materials science & engineering": "Engineering",
    "mechanical engineering": "Engineering",
    "software engineering": "Engineering",

    // Business & Economics
    "accounting": "Business/Economics",
    "actuarial science": "Business/Economics",
    "advertising": "Business/Economics",
    "applied economics and management": "Business/Economics",
    "biomedical studies & finance": "Business/Economics",
    "business": "Business/Economics",
    "business administration": "Business/Economics",
    "business administration & finanical economics": "Business/Economics",
    "business administration & psychology": "Business/Economics",
    "business adminstration": "Business/Economics",
    "business analytics": "Business/Economics",
    "business economics": "Business/Economics",
    "business management": "Business/Economics",
    "business & economics": "Business/Economics",
    "computer information systems": "Business/Economics",
    "computer programming and information systems": "Business/Economics",
    "econ": "Business/Economics",
    "economics": "Business/Economics",
    "economics & african american studies": "Business/Economics",
    "economics & mathematics": "Business/Economics",
    "entrepreneurship": "Business/Economics",
    "finance": "Business/Economics",
    "finance & international business": "Business/Economics",
    "financial economics": "Business/Economics",
    "hospitality management": "Business/Economics",
    "human resources": "Business/Economics",
    "information systems": "Business/Economics",
    "international business": "Business/Economics",
    "management": "Business/Economics",
    "management & economics": "Business/Economics",
    "marketing": "Business/Economics",
    "marketing & advertising": "Business/Economics",
    "marketing management": "Business/Economics",
    "philsophy & politics and economics": "Business/Economics",
    "political economy": "Business/Economics",
    "politics & economics": "Business/Economics",
    "real estate": "Business/Economics",
    "sport management": "Business/Economics",
    "supply chain management": "Business/Economics",

    // Humanities & Social Sciences
    "africana studies": "Humanities/Social Sciences",
    "africana studies & economics & multi-cultural media": "Humanities/Social Sciences",
    "africana studies & political science": "Humanities/Social Sciences",
    "african american studies": "Humanities/Social Sciences",
    "ancient history": "Humanities/Social Sciences",
    "anthropology": "Humanities/Social Sciences",
    "applied psychology": "Humanities/Social Sciences",
    "archaeological studies": "Humanities/Social Sciences",
    "archaeology": "Humanities/Social Sciences",
    "area studies": "Humanities/Social Sciences",
    "art history": "Humanities/Social Sciences",
    "art history & religious studies": "Humanities/Social Sciences",
    "classics": "Humanities/Social Sciences",
    "communication studies": "Humanities/Social Sciences",
    "communications": "Humanities/Social Sciences",
    "comparative literature": "Humanities/Social Sciences",
    "creative writing": "Humanities/Social Sciences",
    "criminal justice": "Humanities/Social Sciences",
    "criminology": "Humanities/Social Sciences",
    "development": "Humanities/Social Sciences",
    "digital journalism": "Humanities/Social Sciences",
    "english": "Humanities/Social Sciences",
    "english & creative writing": "Humanities/Social Sciences",
    "english language & literature": "Humanities/Social Sciences",
    "english literature": "Humanities/Social Sciences",
    "environmental policy": "Humanities/Social Sciences",
    "environmental studies": "Humanities/Social Sciences",
    "environmental studies & economics": "Humanities/Social Sciences",
    "ethics": "Humanities/Social Sciences",
    "foreign languages": "Humanities/Social Sciences",
    "gender studies": "Humanities/Social Sciences",
    "geography": "Humanities/Social Sciences",
    "global affairs": "Humanities/Social Sciences",
    "government": "Humanities/Social Sciences",
    "history": "Humanities/Social Sciences",
    "history of art": "Humanities/Social Sciences",
    "history & politics": "Humanities/Social Sciences",
    "humanities": "Humanities/Social Sciences",
    "industrial and labor relations": "Humanities/Social Sciences",
    "industrial labor relations": "Humanities/Social Sciences",
    "industiral and labor relations": "Humanities/Social Sciences",
    "international development": "Humanities/Social Sciences",
    "international relations": "Humanities/Social Sciences",
    "ir": "Humanities/Social Sciences",
    "journalism": "Humanities/Social Sciences",
    "labor relations": "Humanities/Social Sciences",
    "law": "Humanities/Social Sciences",
    "law & society": "Humanities/Social Sciences",
    "law, history, and society": "Humanities/Social Sciences",
    "liberal arts": "Humanities/Social Sciences",
    "liberal studies": "Humanities/Social Sciences",
    "linguistics": "Humanities/Social Sciences",
    "literature": "Humanities/Social Sciences",
    "magazine": "Humanities/Social Sciences",
    "magazine, news & digital journalism": "Humanities/Social Sciences",
    "mathematics & ancient history": "Humanities/Social Sciences",
    "media arts production": "Humanities/Social Sciences",
    "media studies": "Humanities/Social Sciences",
    "modern languages": "Humanities/Social Sciences",
    "multi-cultural media": "Humanities/Social Sciences",
    "news": "Humanities/Social Sciences",
    "philosophy": "Humanities/Social Sciences",
    "philosophy & journalism": "Humanities/Social Sciences",
    "philosophy & sociology": "Humanities/Social Sciences",
    "philsophy": "Humanities/Social Sciences",
    "policy": "Humanities/Social Sciences",
    "policy studies": "Humanities/Social Sciences",
    "polisci": "Humanities/Social Sciences",
    "political science": "Humanities/Social Sciences",
    "political science & anthropology": "Humanities/Social Sciences",
    "politics": "Humanities/Social Sciences",
    "pre-law": "Humanities/Social Sciences",
    "psych": "Humanities/Social Sciences",
    "psychology": "Humanities/Social Sciences",
    "psychology & political science": "Humanities/Social Sciences",
    "public policy": "Humanities/Social Sciences",
    "public relations": "Humanities/Social Sciences",
    "religious studies": "Humanities/Social Sciences",
    "social anthropology": "Humanities/Social Sciences",
    "social sciences": "Humanities/Social Sciences",
    "sociology": "Humanities/Social Sciences",
    "society": "Humanities/Social Sciences",
    "urban planning": "Humanities/Social Sciences",
    "urban studies": "Humanities/Social Sciences",
    "women's studies": "Humanities/Social Sciences",

    // Arts & Design
    "acting": "Arts/Design",
    "animation": "Arts/Design",
    "art": "Arts/Design",
    "architecture": "Arts/Design",
    "cinema studies": "Arts/Design",
    "collaborative arts": "Arts/Design",
    "dance": "Arts/Design",
    "design": "Arts/Design",
    "design & production": "Arts/Design",
    "digital design": "Arts/Design",
    "digital design & animation": "Arts/Design",
    "drama": "Arts/Design",
    "fashion design": "Arts/Design",
    "fashion merchandising": "Arts/Design",
    "film": "Arts/Design",
    "film production": "Arts/Design",
    "film studies": "Arts/Design",
    "film, photography, and visual arts": "Arts/Design",
    "fine arts": "Arts/Design",
    "flim": "Arts/Design",
    "game design": "Arts/Design",
    "game design and development": "Arts/Design",
    "graphic design": "Arts/Design",
    "industrial design": "Arts/Design",
    "interior design": "Arts/Design",
    "music": "Arts/Design",
    "music composition": "Arts/Design",
    "music performance": "Arts/Design",
    "musical studies": "Arts/Design",
    "performing arts": "Arts/Design",
    "photography": "Arts/Design",
    "politics & flim": "Arts/Design",
    "production": "Arts/Design",
    "studio art": "Arts/Design",
    "theater": "Arts/Design",
    "theatre": "Arts/Design",
    "theatre & english": "Arts/Design",
    "urban design": "Arts/Design",
    "visual arts": "Arts/Design",

    // Health Sciences
    "biomedical studies": "Health Sciences",
    "exercise science": "Health Sciences",
    "food science": "Health Sciences",
    "global public health": "Health Sciences",
    "global public health & biology": "Health Sciences",
    "health sciences": "Health Sciences",
    "hssp": "Health Sciences",
    "kinesiology": "Health Sciences",
    "medicine": "Health Sciences",
    "medicine, science, and the humanities": "Health Sciences",
    "nursing": "Health Sciences",
    "nutrition": "Health Sciences",
    "occupational therapy": "Health Sciences",
    "pharmacology": "Health Sciences",
    "pharmacy": "Health Sciences",
    "physical therapy": "Health Sciences",
    "pre-dental": "Health Sciences",
    "pre-health": "Health Sciences",
    "pre-med": "Health Sciences",
    "pre-medicine": "Health Sciences",
    "pre-pharmacy": "Health Sciences",
    "public health": "Health Sciences",
    "public health science": "Health Sciences",
    "social work": "Health Sciences",
    "speech pathology": "Health Sciences",

    // Education
    "education": "Education",
    "elementary education": "Education",
    "secondary english education": "Education",
    "special education": "Education",
    "teacher tech design": "Education",
    "teaching": "Education",

    // Undecided/Other
    "exploratory": "Undecided/Other",
    "general studies": "Undecided/Other",
    "n/a": "Undecided/Other",
    "other": "Undecided/Other",
    "undecided": "Undecided/Other",
    "undecided major": "Undecided/Other",
};
